# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install -g npm@<6.13.4>
      - run: npm install
      # run tests!
      - run: npm test
